### ISSUE TITLE
Needs Python 3 Compatibility

### ISSUE THREAD

**Issue by cdw9** [sixfeetup/sixfeetup.utils#2]

**Comment by itsthejoker** [comment]
I'm still subscribed to this? 🤔 

Either way, my contribution: https://pythonclock.org/ 😄

**Comment by cdw9** [comment]
I removed you from the developers group a little while back ¯\_(ツ)_/¯ Are you specifically following this repo?

Also I am well aware of the Python clock 😛. Plone is just now getting caught up

**Comment by itsthejoker** [comment]
I was set as watching it. I don't remember ever clicking that, but hey, whatever. Good luck getting Plone up to speed; you'll need it 🙏

**Comment by cdw9** [comment]
version 2.19 with Python 3 compatibility has been released 🎉
